config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :specials do
    collection do
      post :confirm
      patch :confirm
    end
    member do
      patch :confirm
    end
    resources :comments
  end

  resources :favorites, only: [:create, :destroy]
  resources :special_category_relations, only: [:new]
  root 'specials#index'
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true
  belongs_to :special
  belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_special, only: [:create, :edit, :update]
  def create
    @special = Special.find(params[:special_id])
    @comment = @special.comments.build(comment_params)
    @comment.user_id = current_user.id
    respond_to do |format|
      if @comment.save
        # format.html { redirect_to @special, notice: 'コメントが登録されました。' }
        format.js { render :index }
      else
        format.html { redirect_to special_path(@special), notice: 'コメントが登録できませんでした。' }
      end
    end
  end

  def edit
    @comment = @special.comments.find(params[:id])
    respond_to do |format|
      flash.now[:notice] = 'コメントの編集中'
      format.js { render :edit }
    end
  end

  def update
    @comment = @special.comments.find(params[:id])
    # @special = @comment.special
    respond_to do |format|
      if @comment.update(comment_params)
        # redirect_to special_path(@special), notice: 'コメントが更新されました。'
        flash.now[:notice] = 'コメントが編集されました'
        format.js { render :index }
      else
        flash.now[:notice] = 'コメントの編集に失敗しました'
        format.js { render :edit_error }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    if @comment.destroy
      respond_to do |format|
        format.js { render :index }
      end
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:special_id, :content)
  end
  def set_special
    @special = Special.find(params[:special_id])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_edit.html.erb
<%= form_with(model: [special, comment]) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p><%= notice %></p>
  <div class="field">
    <%= form.text_area :content, id: "comment_content_#{special.id}", size: "90x3"  %>
    <%= form.label :' ' %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/_form.html.erb
<%= form_with(model: [special, comment]) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
        <%= form.label :あなたのコメントを書きましょう %>
    　　<%= form.text_area :content, size: "110x3" %>
  </div>
  <div class="actions">
    　　<%= form.submit value="コメントを登録する" %>
  </div>
<% end %>

app/views/comments/_index.html.erb
<ul>
  <% comments.each do |comment| %>
    <% if comment.id.present? %>
      <div>
        <div class="comment-content" id ="this_comment_<%= comment.id %>"></div>
        <% if comment.user.try(:name) %>
        ★<%= comment.user.name %>さん 　　 <%= comment.updated_at.strftime("%Y年%m月%d日 %H:%M") %><br><br>
        <%= comment.content %><br>
        <% else %>
          Not User Data<br>
        <% end %>

        <% if comment.user == current_user %>
          <p>
            <%= link_to "コメント編集", edit_special_comment_path(special, comment), remote: true %>
            <%= link_to "コメント削除", special_comment_path(comment.special_id, comment.id), method: :delete, remote: true,
                                data: { confirm: "本当に削除しますか?"} %>
          </p>
        <% end %>
        <hr noshade>
      </div>
    <% end %>
  <% end %>
</ul>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/edit.js.erb
$("#this_comment_<%= @comment.id %>").replaceWith("<%= j render 'comments/edit', special: @special, comment: @comment %>");
$("#notice").html("<%= j flash[:notice] %>");

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'comments/index', { comments: @comment.special.comments, special: @comment.special }) %>")
$("textarea").val('');
$("#notice").html("<%= j flash[:notice] %>");