config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :specials do
    collection do
      post :confirm
      patch :confirm
    end
    member do
      patch :confirm
    end
    resources :comments
  end

  resources :favorites, only: [:create, :destroy]
  resources :special_category_relations, only: [:new]
  root 'specials#index'
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/special.rb
class Special < ApplicationRecord
    validates :product, presence: true
    validates :company, presence: true
    validates :detail, presence: true
    validates :per, numericality: { :greater_than => 0 }
    validates :status, presence: true
    validates :price, numericality: {only_integer: true, greater_than_or_equal_to: 0}

    mount_uploader :image, ImageUploader
    has_many :favorites, dependent: :destroy
    has_many :comments, dependent: :destroy
    has_many :suiis, dependent: :destroy
    has_many :special_category_relations, dependent: :destroy
    has_many :categories, through: :special_category_relations
    # enum status: { '割安': 0, '並': 1, '割高': 2 }
end

app/controllers/specials_controller.rb
class SpecialsController < ApplicationController
  before_action :set_special, only: [:show, :edit, :update, :destroy]
  before_action :login_check, only: [:show]
  # before_action :authenticate_user!
  PER = 5

  def index
    @categories = Category.all
    @specials = Special.page(params[:page]).per(PER)
    @specials = @specials.order(updated_at: :desc)

    if params[:category_id].present?
  #presentメソッドでparams[:category_id]に値が含まれているか確認 => trueの場合下記を実行
      @category = Category.find(params[:category_id])
      @specials = @category.specials.page(params[:page]).per(PER)
    end

    if params[:sort_per_low]
      @specials = Special.page(params[:page]).per(PER)
      @specials = @specials.order(per: :asc)
    end

    if params[:sort_price_low]
      @specials = Special.page(params[:page]).per(PER)
      @specials = @specials.order(price: :asc)
    end

    if params[:my_favorite]
      @user = current_user
      @favorites = current_user.favorite_specials.all
      @specials = @favorites.page(params[:page]).per(PER)
    end


  end

  def new
    if current_user.try(:admin?)
      @special = Special.new
    else
      redirect_to specials_path, notice: "あなたは優待投稿ができません"
    end
  end

  def edit
    if current_user.try(:admin?)
      @special = Special.find(params[:id])
    else
      redirect_to specials_path, notice: "あなたは優待編集ができません"
    end
  end

  def create
    @special = Special.new(special_params)
    if params[:back]
      render :new
    else
      if @special.save
        redirect_to specials_path, notice: "優待記事を作成しました！"
      else
        render :new
      end
    end
  end

  def update
    # @special = Special.includes(:user).find(params[:id])
    if @special.update(special_params)
      redirect_to specials_path, notice: "優待記事を編集しました！"
    else
      render :edit
    end
  end

  def show
    @categories = Category.all
    @special = Special.find(params[:id])
    @favorite = current_user.favorites.find_by(special_id: @special.id)
    @comments = @special.comments
    @comment = @special.comments.build
    @suiis = @special.suiis
    if params[:category_id].present?
  #presentメソッドでparams[:category_id]に値が含まれているか確認 => trueの場合下記を実行
      @category = Category.find(params[:category_id])
      @specials = @category.specials
    end
  end

  def destroy
    @special.destroy
    redirect_to specials_path, notice:"優待記事を削除しました！"
  end

  def confirm
    @special = Special.new(special_params)
    render :new if @special.invalid?
  end


  private
  def special_params
    params.require(:special).permit(:product, :company, :detail, :per, :status, :price, :image, :image_cache, category_ids: [])
  end
  def set_special
    @special = Special.find(params[:id])
  end
  def login_check
    unless user_signed_in?
      flash[:alert] = "ログインしてください"
      redirect_to root_path
    end
  end

end

app/helpers/specials_helper.rb
module SpecialsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm' || action_name == 'create'
      confirm_specials_path
    elsif action_name == 'edit'
      special_path
    end
  end

  # def confirm_new_or_edit
  #   # 優待記事新規投稿とアップデートに分岐したいが…
  #   unless @special.id?
  #     specials_path
  #   else
  #     special_path
  #   end
  # end

  def confirm_form_method
    @special.id ? 'patch' : 'post'
  end
end

app/views/specials/_form.html.erb
<%= form_with(model: @special, local: true, url: choose_new_or_edit) do |form| %>
  <% if @special.errors.any? %>
    <div id="error_explanation">
      <h2><%= @special.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @special.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="special_title">
    <%= form.label :"優待製品名" %>
    <%= form.text_field :product %>
  </div>
  <div class="special_title">
    <%= form.label :"会社名" %>
    <%= form.text_field :company %>
  </div>
  <div class="special_title">
    <%= form.label :"優待製品写真" %>
    <%= form.file_field :image %>
  </div>
  <div class="special_title">
    <%= form.label :"優待解説" %>
    <%= form.text_area :detail, :size=>"100x5" %>
  </div>
  <div class="special_title">
    <%= form.label :PER %>
    <%= form.text_field :per %>
  </div>
  <div class="special_title">
    <%= form.label :"割安状況" %>
    <%= form.select :status, [["割安", "割安"], ["並", "並"], ["割高", "割高"]], include_blank: "選択して下さい" %>
  </div>
  <div class="special_title">
    <%= form.label :"100株の取得価格" %>
    <%= form.text_field :price %>
  </div>
  <div>
    <%= form.label :category, 'カテゴリ' %>
    <%= form.collection_check_boxes(:category_ids, Category.all, :id, :name) do |category| %>
      <%= category.label do %>
        <%= category.check_box %>
        <%= category.text %>
      <% end %>
    <% end %>
  </div>
  <%= form.submit %>
<% end %>

<%= link_to "優待記事一覧画面にもどる", specials_path %>

app/views/specials/confirm.html.erb
<div class="container">
  <div id="contents" class="col-sm-9 col-xs-9 col-md-9 col-lg-9" style="background: #FFFFFF;">
    <h3>以下の内容で、送信する。</h3>

    <%= form_with(model: @special, url: specials_path, local: true) do |form| %>
      <%= form.hidden_field :product %>
      <%= form.hidden_field :company %>
      <%= form.hidden_field :image_cache %>
      <%= form.hidden_field :detail %>
      <%= form.hidden_field :per %>
      <%= form.hidden_field :status %>
      <%= form.hidden_field :price %>

      <p>優待製品名：<%= @special.product %></p>
      <p>会社名：<%= @special.company %></p>
      <p>写真：<%= image_tag(@special.image.url) if @special.image && @special.image.url %></p>
      <p>優待解説：<%= @special.detail %></p>
      <p>PER：<%= @special.per %></p>
      <p>割安状況：<%= @special.status %></p>
      <p>100株の取得価格：<%= @special.price %></p>
      <p><%= form.label :category, 'カテゴリ' %>
      <%= form.collection_check_boxes(:category_ids, Category.all, :id, :name) do |category| %>
        <%= category.label do %>
          <%= category.check_box %>
          <%= category.text %>
        <% end %>
      <% end %>
      </p>
      <!-- <p>カテゴリー：<% @special.categories.each do |category| %><%= category.name %><% end %></p> -->

      <%= form.submit "登録する" %>
      <%= form.submit "戻る", name: 'back' %>
      <% end %>
    </div>
</div>

app/views/specials/edit.html.erb
<div class="container">
  <div id="contents" class="col-sm-9 col-xs-9 col-md-9 col-lg-9" style="background: #FFFFFF;">
    <h2>優待記事を編集する</h2>
    <%= render 'form' %>
</div>
</div>

app/views/specials/index.html.erb
<!-- サイドバー -->
<div class="container">
<!-- <img src="/assets/logo.jpg" alt="" width="292" height="75"><br> -->
<% if user_signed_in? %>
ようこそ！<%= current_user.name %>さん<br>
<% else %>
会員登録しましょう。全部閲覧、カテゴリ検索が利用できます。<br>
<% end %>
<p><%= notice %></p>
  <div class="row">
    <div id="sidebar" class="col-sm-2 col-xs-2 col-md-2 col-lg-2" style="background: #FFFFFF;">
      <img src="/assets/a_company.jpg" alt="" width="141" height="50"><br>
      <img src="/assets/b_company.jpg" alt="" width="141" height="50"><br>
      ■■カテゴリ一覧<br><br>
      <% @categories.each do |category| %>
        <% if user_signed_in? %>
          　<%= link_to category.name, specials_path(category_id: category.id) %><br>
        <% else %>
          　<%= category.name %><br>
        <% end %>
      <% end %>
    </div>

  <!-- コンテンツ -->
    <div id="contents" class="col-sm-9 col-xs-9 col-md-9 col-lg-9" style="background: #FFFFFF;">
      <% if user_signed_in? %>
        <%= link_to "▼PER低い順でソート", specials_path(sort_per_low: "true") %>　　　
        <%= link_to "▼取得価格順にソート", specials_path(sort_price_low: "true") %>　　　
        <%= link_to "▼お気に入りを表示", specials_path(my_favorite: "true") %>
      <% else %>
        ▼PER低い順でソート（ログイン時のみ利用可能）　　　
        ▼取得価格順にソート（ログイン時のみ利用可能）　　　
        ▼お気に入りを表示（ログイン時のみ利用可能）
      <% end %>
      <table class="table table-hover">
        <thead>
          <tr>
            <th scope="col">優待製品名</th>
            <th scope="col">会社名</th>
            <th scope="col">写真</th>
            <th scope="col">100株の取得価格</th>
            <th scope="col">PER</th>
            <th scope="col">詳細リンク</th>
          </tr>
        </thead>
        <tbody>
          <% @specials.each do |special| %>
            <tr>
              <th scope="row"><%= special.product %></th>
              <td><%= special.company %></td>
              <td><%= image_tag special.image.url ,class: "index_image" if special.image? %></td>
              <td><%= special.price %></td>
              <td><%= special.per %><br><span class="badge badge-danger"><%= special.status %></span>
              </td>
              <td><% if user_signed_in? %><%= link_to '詳細ページへ', special_path(special.id) %><% end %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <% if user_signed_in? %>
        <%= paginate @specials %>
      <% end %>
    </div>
  </div>
  <% if current_user.try(:admin?) %>
  <%= link_to '新しく優待を投稿する', new_special_path %>
  <% end %>
</div>

app/views/specials/new.html.erb
<div class="container">
  <div id="contents" class="col-sm-9 col-xs-9 col-md-9 col-lg-9" style="background: #FFFFFF;">
    <h2>優待記事を作成する</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/specials/show.html.erb
<div class="container">
<!-- <img src="/assets/logo.jpg" alt="" width="292" height="75"><br> -->
<% if user_signed_in? %>
ようこそ！<%= current_user.name %>さん<br>
<p><%= notice %></p>
<% end %>
  <div class="row">
    <div id="sidebar" class="col-sm-2 col-xs-2 col-md-2 col-lg-2" style="background: #FFFFFF;">
      ■■カテゴリ一覧<br><br>
      <% @categories.each do |category| %>
        　<%= link_to category.name, specials_path(category_id: category.id) %><br>
      <% end %>
    </div>

  <!-- コンテンツ -->
    <div id="contents" class="col-sm-9 col-xs-9 col-md-9 col-lg-9" style="background: #FFFFFF;">
      <% if @favorite.present? %>
        <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
      <% else %>
        <%= link_to 'お気に入りする', favorites_path(special_id: @special.id), method: :post, class: 'btn btn-primary' %>
      <% end %>
      <table class="table table-hover">
        <tr><th>商品名</th><td><%= @special.product %></td></tr>
        <tr><th>会社名</th><td><%= @special.company %></td></tr>
        <tr><th>写真</th><td><%= image_tag @special.image.url ,class: "show_image" if @special.image? %></td></tr>
        <tr><th>解説</th><td><%= @special.detail %></td></tr>
        <tr><th>100株の取得価格</th><td><%= @special.price %></td></tr>
        <tr><th>PER</th><td><%= @special.per %><br><span class="badge badge-danger"><%= @special.status %></span></td></tr>
        <tr><th>カテゴリ</th><td>
        <% @special.categories.each do |category| %>
          <%= category.name %>
        <% end %>
        </td></tr>
      </table>
      ■株価の推移（100株の価格）
      <%= line_chart @suiis.group(:date_friday).sum(:weekly_closing_price), min: nil %>
      <hr noshade>
      <img src="/assets/a_company.jpg" alt="" width="141" height="50">  <img src="/assets/b_company.jpg" alt="" width="141" height="50"><br>
      <hr noshade>

        <%= render partial: 'comments/form', locals: { comment: @comment, special: @special } %>
        <hr noshade>
      <!-- 投稿されたコメント一覧をブログの詳細ページに表示するためのrender -->
      <div id="comments_area">
        <%= render partial: 'comments/index', locals: { comments: @comments, special: @special } %>
      </div>
      <hr noshade>
    <!-- コメント入力欄をブログの詳細ページに表示するためのrender -->

      <%= link_to "優待記事一覧画面にもどる", specials_path %>
      <div>
        <% if current_user.try(:admin?) %>
        <td><%= link_to "編集する", "/specials/#{@special.id}/edit" %></td>
        <td><%= link_to '削除する', special_path, method: :delete ,data: { confirm: '本当に削除していいですか？' } %></td>
        <% end %>
      </div>
    </div>
  </div>
</div>