config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :specials do
    collection do
      post :confirm
      patch :confirm
    end
    member do
      patch :confirm
    end
    resources :comments
  end

  resources :favorites, only: [:create, :destroy]
  resources :special_category_relations, only: [:new]
  root 'specials#index'
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>株主優待.com</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
        <span class="sr-only">株主優待.com</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand"><img src="/assets/logo.jpg" alt="" width="130" height="32"></a>
    </div>
    <div id="gnavi" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to 'TOP（優待一覧）',specials_path %></li>
          <li><%= link_to "会員情報変更", edit_user_registration_path %></li>
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'TOP（優待一覧）', specials_path %></li>
          <li><%= link_to "ログイン", new_user_session_path %></li>
          <li><%= link_to "会員登録", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
  </nav>
  <body>
    <%= yield %>
  </body>
</html>